baseurl = "https://firefart.at"
languageCode = "en-us"
title = "FireFart"
theme = "purehugo"
copyright = "Copyright by Christian Mehlmauer"
ignoreFiles = [ "^\\.DS_Store$" ]

[params]
  twitterName = "_FireFart_"
  githubName = "FireFart"
  description = "that austrian security guy"
  author = "Christian Mehlmauer"
